export enum Country {
  INDIA = 'India',
}

export enum State {
  ANDHRA_PRADESH = 'Andhra Pradesh',
  ARUNACHAL_PRADESH = 'Arunachal Pradesh',
  ASSAM = 'Assam',
  BIHAR = 'Bihar',
  CHHATTISGARH = 'Chhattisgarh',
  GOA = 'Goa',
  GUJARAT = 'Gujarat',
  HARYANA = 'Haryana',
  HIMACHAL_PRADESH = 'Himachal Pradesh',
  JHARKHAND = 'Jharkhand',
  KARNATAKA = 'Karnataka',
  KERALA = 'Kerala',
  MADHYA_PRADESH = 'Madhya Pradesh',
  MAHARASHTRA = 'Maharashtra',
  MANIPUR = 'Manipur',
  MEGHALAYA = 'Meghalaya',
  MIZORAM = 'Mizoram',
  NAGALAND = 'Nagaland',
  ODISHA = 'Odisha',
  PUNJAB = 'Punjab',
  RAJASTHAN = 'Rajasthan',
  SIKKIM = 'Sikkim',
  TAMIL_NADU = 'Tamil Nadu',
  TELANGANA = 'Telangana',
  TRIPURA = 'Tripura',
  UTTAR_PRADESH = 'Uttar Pradesh',
  UTTARAKHAND = 'Uttarakhand',
  WEST_BENGAL = 'West Bengal',
  ANDAMAN_NICOBAR = 'Andaman and Nicobar Islands',
  CHANDIGARH = 'Chandigarh',
  DADRA_NAGAR_HAVELI = 'Dadra and Nagar Haveli and Daman and Diu',
  DELHI = 'Delhi',
  JAMMU_KASHMIR = 'Jammu and Kashmir',
  LADAKH = 'Ladakh',
  LAKSHADWEEP = 'Lakshadweep',
  PUDUCHERRY = 'Puducherry',
}

export enum City {
  // Deprecated: Use STATE_TO_CITIES mapping for validation and dropdowns
  MUMBAI = 'Mumbai',
  PUNE = 'Pune',
  BANGALORE = 'Bangalore',
  DELHI = 'Delhi',
  CHENNAI = 'Chennai',
  KOLKATA = 'Kolkata',
  LUCKNOW = 'Lucknow',
  RAIPUR = 'Raipur'
}

export const STATE_TO_CITIES: { [key in State]: string[] } = {
  [State.ANDHRA_PRADESH]: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool'],
  [State.ARUNACHAL_PRADESH]: ['Itanagar', 'Naharlagun', 'Pasighat'],
  [State.ASSAM]: ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat'],
  [State.BIHAR]: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur'],
  [State.CHHATTISGARH]: ['Raipur', 'Bhilai', 'Bilaspur'],
  [State.GOA]: ['Panaji', 'Margao', 'Vasco da Gama'],
  [State.GUJARAT]: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
  [State.HARYANA]: ['Faridabad', 'Gurugram', 'Panipat', 'Ambala'],
  [State.HIMACHAL_PRADESH]: ['Shimla', 'Mandi', 'Solan'],
  [State.JHARKHAND]: ['Ranchi', 'Jamshedpur', 'Dhanbad'],
  [State.KARNATAKA]: ['Bangalore', 'Mysore', 'Mangalore', 'Hubli'],
  [State.KERALA]: ['Thiruvananthapuram', 'Kochi', 'Kozhikode'],
  [State.MADHYA_PRADESH]: ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior'],
  [State.MAHARASHTRA]: ['Mumbai', 'Pune', 'Nagpur', 'Nashik'],
  [State.MANIPUR]: ['Imphal'],
  [State.MEGHALAYA]: ['Shillong'],
  [State.MIZORAM]: ['Aizawl'],
  [State.NAGALAND]: ['Dimapur', 'Kohima'],
  [State.ODISHA]: ['Bhubaneswar', 'Cuttack', 'Rourkela'],
  [State.PUNJAB]: ['Ludhiana', 'Amritsar', 'Jalandhar'],
  [State.RAJASTHAN]: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota'],
  [State.SIKKIM]: ['Gangtok'],
  [State.TAMIL_NADU]: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'],
  [State.TELANGANA]: ['Hyderabad', 'Warangal'],
  [State.TRIPURA]: ['Agartala'],
  [State.UTTAR_PRADESH]: ['Lucknow', 'Kanpur', 'Ghaziabad', 'Agra'],
  [State.UTTARAKHAND]: ['Dehradun', 'Haridwar'],
  [State.WEST_BENGAL]: ['Kolkata', 'Howrah', 'Durgapur', 'Asansol'],
  [State.ANDAMAN_NICOBAR]: ['Port Blair'],
  [State.CHANDIGARH]: ['Chandigarh'],
  [State.DADRA_NAGAR_HAVELI]: ['Silvassa', 'Daman'],
  [State.DELHI]: ['New Delhi', 'Delhi'],
  [State.JAMMU_KASHMIR]: ['Srinagar', 'Jammu'],
  [State.LADAKH]: ['Leh', 'Kargil'],
  [State.LAKSHADWEEP]: ['Kavaratti'],
  [State.PUDUCHERRY]: ['Puducherry', 'Karaikal'],
}; 